### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [juanmism/4Geeks-Instagram-post#1]
Hola Juanmi,

✔ En general muy bien el ejercicio. Has hecho exactamente lo que se pedía y se ve muy bien. Además, has usado _flexbox_ para alinear los elementos que se lo que se aconseja en lugar de `float`. 

☝ **_Consejos / Mejoras_**:
- Al div `<div class="head">` que tienes en la línea 13 le has asignado la propiedad `display: flex;`. Esto es lo más correcto, porque estás indicando que quieres que todos los "hijos" (es decir, los que tiene directamente debajo) de este div se alineen siguiendo la lógica de flexbox. 

El problema es que has aplicado `margin-left: 360px;` a su tercer hijo (es decir, al div con la clase `.elipsis`) entiendo que para forzar que se coloque en el extremo derecho. Esto se consigue añadiendo la propiedad `justify-content: space-between` a `.head`, y de esta manera te ahorras establecer márgenes y dimensiones fijas que pueden ocasionar errores en un momento dado. Con `justify-content` lo que haces es indicar exactamente el modo en el que los elementos se van a alinear horizontalmente. 

Esta mísma lógica es la que podrías haber aplicado directamente en el div `.icons` que tienes debajo de la foto y así te ahorrarías aplicar mucho CSS y además ahorrarte posibles errores.

Puedes leer más sobre flexbox aquí: https://developer.mozilla.org/es/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

Si tienes alguna duda puedes preguntarnos sin problemas.

Te apruebo el ejercicio pero te animo a modificarlo aplicando los cambios que te he comentado (si tienes tiempo). Si lo haces, avísame y le vuelvo a echar un vistazo.

**Comment by juanmism** [comment]
Acabo de realizar las modificaciones que me recomendaste. Cuando puedas le echas un vistazo y me dices. Gracias.

**Comment by juanmism** [comment]
Hola Jose.
Acabo de hacer las modificaciones que me indicaste.
En GITHUB te he hecho un comentario en "issues" de este ejercicio.
Dime, para la próxima corrección de siguientes ejercicios, si te tengo que
enviar un correo para que lo revises o te llegan las notificaciones cada
vez que hacemos un comentario en GITHUB sobre el ejercicio en cuestión.
Mañana te envío las dudas que me vayan surgiendo para la mentoría del
viernes.
Un cordial saludo.
Juan M. Sáenz

**Comment by m4n50n** [comment]
Hola Juanmi,

lo acabo de revisar. Todo perfecto con flexbox. Cualquier issue o comentario que pongas me llega la notificación, así que no es necesario que me avises.

Gracias!
